version: '3.4'

services:
  back:
    container_name: back
    build:
      context: .
      target: back
    volumes:
      - ./backend:/code
      - /code/node_modules
    ports:
      - "3333:3333"
    links:
      - mongo
  
  front:
    container_name: front
    build: 
      context: .
      target: front
    volumes:
      - ./web:/code
      - /code/node_modules
    ports:
      - "3000:3000"
    links:
      - back
  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"